config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, skip: [:passwords] # TODO: :registrations if configured
  root 'sites#home'
  resources :batches, only: %i[index new create destroy] do
    namespace :step do
      %i[preprocesses processes transfers archives].each do |step|
        resources step, only: %i[new create show] do
          post 'cancel'
          post 'reset'
        end
      end
    end
  end
  resources :connections, except: %i[index show]
  get '/connections', to: redirect('/connections/new')
  get '/connections/:id', to: redirect('/connections/%{id}/edit')
  resources :groups, only: %i[index new create edit update destroy]
  get '/groups/:id', to: redirect('/groups/%{id}/edit')
  resources :mappers, only: %i[index]
  get '/mappers/autocomplete', to: 'mappers#autocomplete'
  resources :users, except: %i[create new show] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
  get '/users/:id', to: redirect('/users/%{id}/edit')
  get '/users/:id/group', to: redirect('/users/%{id}/edit')
  patch '/users/:id/group', to: 'users#update_group', as: 'user_group'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :batches, dependent: :destroy
  has_many :connections, dependent: :destroy
  belongs_to :group # this is the current group
  has_many :affiliations
  has_many :groups, through: :affiliations do
    def <<(new_item)
      super(Array(new_item) - proxy_association.owner.groups)
    end
  end
  belongs_to :role
  after_initialize :setup, if: :new_record?
  before_save :reset_admin_group
  validate :group_is_affiliated, unless: :new_record?
  validates :superuser, uniqueness: true, if: -> { superuser }
  scope :superuser, -> { where(superuser: true).first }
  scope :admins, -> { where(role_id: Role.default_scoped.admin.id) }

  def active_for_authentication?
    super && active?
  end

  def active?
    active
  end

  def admin?
    role == Role.default_scoped.admin
  end

  # TODO: test
  def affiliated_with?(group)
    groups.exists?(group.id)
  end

  def default_connection
    connection = connections.where(primary: true).first
    connection ||= connections.where(enabled: true).first
    connection
  end

  def disabled?
    !enabled?
  end

  def enabled?
    enabled && group.enabled?
  end

  def group?(group)
    self.group == group
  end

  def is?(user)
    self == user
  end

  def manage?(record)
    "Role::#{role.name}".constantize.new(self).manage?(record)
  end

  def manager?
    role == Role.manager
  end

  def member?
    role == Role.member
  end

  def owner_of?(record)
    self == record.user if record.respond_to?(:user)
  end

  def role?(name)
    role.name == name
  end

  def setup
    self.group ||= target_group
    groups << self.group # add this group to our list of affiliate groups
    self.role ||= target_role
    self.enabled ||= self.role == Role.manager
  end

  def superuser?
    is?(User.superuser)
  end

  def self.superuser_created?
    User.superuser
  end

  private

  def group_is_affiliated
    unless affiliations.where(group: group).one?
      errors.add(:group, I18n.t('user.unaffiliated_group'))
    end
  end

  def reset_admin_group
    if self.role == Role.admin && self.group != Group.default
      self.group = Group.default
      groups.destroy_all
      groups << Groups.all
    end
  end

  def target_group
    g = Group.matching_domain?(email.split('@').last)
    g.any? ? g.first : Group.default
  end

  def target_role
    if self.group != Group.default && self.group.users.where.not(role: Role.admin).count.zero?
      Role.manager
    else
      Role.default
    end
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  before_action :set_user, only: %i[edit update update_group destroy]
  before_action :check_for_illegal_promote_to_admin, only: %i[update]

  def index
    authorize(User)
    @pagy, @users = pagy(
      policy_scope(User).includes(:group, :role).order('groups.name asc, users.email asc')
    )
  end

  def edit
    @connections = @user.connections.order(:name)
  end

  def update
    respond_to do |format|
      scrub_params(:user, :password)
      scrub_params(:user, :password_confirmation)
      affiliate_user_with_group

      if @user.update(user_params)
        # reset_user(@user)
        format.html do
          redirect_to edit_user_path(@user),
                      notice: t('action.updated', record: 'User')
        end
      else
        @connections = @user.connections.order(:name)
        format.html { render :edit }
      end
    end
  end

  def update_group
    respond_to do |format|
      if @user.group.update(user_group_params)
        format.html do
          redirect_to edit_user_path(@user), notice: t('user.group_updated')
        end
      else
        format.html do
          redirect_to edit_user_path(@user), alert: error_messages(@user.group.errors)
        end
      end
    end
  end

  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: t('action.deleted', record: 'User') }
    end
  end

  # Become user functionality
  def impersonate
    user = authorize User.find(params[:id])
    impersonate_user(user)
    redirect_back fallback_location: root_path
  end

  def stop_impersonating
    stop_impersonating_user
    redirect_to root_path
  end

  private

  def affiliate_user_with_group
    if current_user.admin? && !@user.admin?
      group_id = params.dig(:user, :group_id) || params[:group_id]
      @user.groups << Group.find(group_id) if group_id
    end
  end

  def check_for_illegal_promote_to_admin
    role_id = params.dig(:user, :role_id) || params[:role_id]
    if !current_user.admin? && role_id && Role.find(role_id).name == Role::TYPE[:admin]
      raise Pundit::NotAuthorizedError
    end
  end

  def reset_user(user)
    current_user.is?(user) ? bypass_sign_in(user) : bypass_sign_in(current_user)
  end

  def set_user
    @user = authorize User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(policy(@user).permitted_attributes)
  end

  def user_group_params
    params.require(:group).permit(:name, :email, :profile)
  end
end

app/views/users/_affiliations.html.erb
<h2 class="subtitle">
  <%= t('user.affiliations') %>
</h2>
<% if !current_user.is?(user) %>
  <div class="notification is-info is-light mt-3">
    <%= raw t('user.editing_affiliations', email: current_user.email) %>
  </div>
<% end %>
<table class="table is-fullwidth is-hoverable">
  <thead>
    <tr>
      <th><%= t 'group.name' %></th>
      <th><%= t 'group.enabled' %></th>
      <th><%= t 'user.affiliated' %></th>
  </thead>

  <tbody>
    <%= render partial: 'affiliations/row',\
        collection: current_user.affiliations,
        as: :affiliation,
        locals: { user: user }
    %>
  </tbody>
</table>

app/views/users/_connections.html.erb
<table class="table is-fullwidth is-hoverable">
  <thead>
    <tr>
      <th><%= t 'connection.name' %></th>
      <th><%= t 'connection.enabled' %></th>
      <th><%= t 'connection.primary' %></th>
      <th colspan="1"></th>
  </thead>

  <tbody>
    <%= render partial: 'connections/row',\
        collection: @connections,
        as: :connection,
        locals: { user: user }
    %>
  </tbody>
</table>

app/views/users/_form.html.erb
<div class="columns">
  <div class="column">
    <h2 class="subtitle"><%= t('user.title.account') %></h2>
    <%= form_with(model: user, local: true) do |form| %>
      <div class="field">
        <%= form.label t('user.email'), class: 'label' %>
        <%= content_tag :div, class: 'control has-icons-left' do %>
          <%= form.email_field :email, disabled: true, class: 'input' %>
          <%= render partial: 'shared/icon',
              locals: { classes: 'is-small is-left', icon: 'envelope' }
          %>
        <% end %>
      </div>

      <div class="field">
        <%= form.label t('user.password'), class: 'label' %>
        <%= content_tag :div, class: 'control has-icons-left' do %>
          <%= form.password_field :password, :autocomplete => "new-password",
              class: 'input' %>
          <%= render partial: 'shared/icon',
              locals: { classes: 'is-small is-left', icon: 'key' }
          %>
        <% end %>
      </div>

      <div class="field">
        <%= form.label t('user.password_confirmation'), class: 'label' %>
        <%= content_tag :div, class: 'control has-icons-left' do %>
          <%= form.password_field :password_confirmation,
              class: 'input' %>
          <%= render partial: 'shared/icon',
              locals: { classes: 'is-small is-left', icon: 'key' }
          %>
        <% end %>
      </div>

      <div class="field">
        <%= form.label t('user.enabled'), class: 'checkbox' do %>
          <%= content_tag :span, class: 'mr-1' do t('user.enabled') ; end %>
          <%= form.check_box :enabled, disabled: current_user.is?(user) %>
          <% if user.group.disabled? %>
            <%= content_tag :span, class: 'has-text-danger is-italic ml-1' do %>
              (<%= t('group.disabled') %>)
            <% end %>
          <% end %>
        <% end %>
      </div>

      <%= content_tag :div, class: 'columns' do %>
        <%= content_tag :div, class: 'column' do %>
          <div class="field">
            <%= form.label t('user.role'), class: 'label' %>
            <div class="select is-fullwidth">
              <%= form.collection_select :role_id, Role.select_options(current_user), :id, :name,
                  { selected: user.role_id }, disabled: current_user.is?(user) %>
            </div>
          </div>
        <% end %>
        <%= content_tag :div, class: 'column' do %>
          <% unless user.admin? %>
            <div class="field">
              <%= form.label t('user.group'), class: 'label' %>
              <div class="select is-fullwidth">
                <%= form.collection_select :group_id, switchable_groups(Group.select_options_without_default(user)),
                :id, :name, { selected: user.group_id }, disabled: !can_edit_user_group?(user) %>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>

      <div class="field is-grouped mt-5">
        <div class="control">
          <%= form.submit t('action.submit'), class: 'button is-link' %>
        </div>
        <div class="control">
          <% if impersonating_user? %>
            <%= link_to t('action.cancel'), root_path, class: 'button is-info' %>
          <% else %>
            <%= link_to t('action.cancel'), users_path, class: 'button is-info' %>
          <% end %>
        </div>
        <% if !current_user.is?(user) && current_user.admin? %>
        <div class="control">
          <%=
            link_to t('navigation.become'), impersonate_user_path(user),
            method: :post, class: 'button is-primary'
          %>
        </div>
        <% end %>
      </div>
    <% end %>
    <div class="level"></div>
    <hr/>
    <% if current_user.is?(user) && !user.group.default? && manage?(user.group) %>
      <%= render partial: 'group', locals: { user: user } %>
    <% end %>
  </div>
  <div class="column">
    <div class="level">
      <div class="level-left">
        <h2 class="subtitle">
          <%= t('connection.title.index') %>
        </h2>
      </div>
      <div class="level-right">
        <% if current_user.is?(user) %>
          <%= content_tag :div, class: 'tags has-addons mt-2' do %>
            <%= render partial: 'shared/button_create',
                locals: { path: new_connection_path(user_id: user.id), text: t('connection.action.create') } %>
          <% end %>
        <% end %>
      </div>
    </div>
    <%= render partial: 'connections', locals: { user: user } %>
    <% if can_affiliate?(user) %>
      <hr/>
      <%= render partial: 'affiliations', locals: { user: user } %>
    <% end %>
  </div>
</div>

app/views/users/_group.html.erb
<h2 class="subtitle"><%= t('group.title.name') %></h2>
<%= form_with(model: user.group, url: user_group_path(user), local: true) do |form| %>
  <div class="field">
    <%= form.label :name, class: 'label' %>
    <%= form.text_field :name, class: 'input' %>
  </div>
  <div class="field">
    <%= form.label :email, class: 'label' %>
    <%= form.text_field :email, class: 'input' %>
  </div>
  <%= content_tag :div, class: 'field',
      'data-controller': 'autocomplete',
      'data-autocomplete-url': "/mappers/autocomplete" do %>
    <%= form.label :profile, class: 'label' %>
    <%= form.text_field :profile,
      class: 'input',
      placeholder: t('group.placeholder.profile_version'),
      'data-action': 'autocomplete#update',
      'data-target': 'autocomplete.field'
    %>
  <% end %>
  <div class="field is-grouped mt-5">
    <div class="control">
      <%= form.submit t('action.submit'), class: 'button is-link' %>
    </div>
  </div>
<% end %>

app/views/users/_row.html.erb
<tr id="<%= dom_id(user) %>" data-user-id="<%= user.id %>">
  <td>
    <% if manage?(user) && !user.superuser? %>
      <%= link_to edit_user_path(user) do %>
        <%= render partial: 'user', locals: { icon: 'pencil', user: user } %>
      <% end %>
    <% else %>
      <%= render partial: 'user', locals: { icon: 'user', user: user } %>
    <% end %>
  </td>
  <td><%= user.group.name %></td>
  <td><%= user.role.name %></td>
  <td>
    <% if user.enabled? %>
      <%= render partial: 'shared/icon',
          locals: { classes: 'has-text-success', icon: 'thumbs-up' }
      %>
    <% else %>
      <%= render partial: 'shared/icon',
          locals: { classes: 'has-text-danger', icon: 'ban' }
      %>
    <% end %>
    <% if can_toggle_status?(user) %>
      <%= check_box_tag nil, nil, user.enabled?,
        {
          id: "toggle_status_#{dom_id(user)}",
          data: {
            'reflex': 'click->Application#toggle_status',
            'reflex-dataset': 'combined',
            'model': 'user',
            'id': user.id
          }
        }
      %>
    <% end %>
  </td>
  <td><%= user.connections.size %></td>
  <% if admin? %>
    <td>
      <%= content_tag :div, class: 'tags has-addons is-outline' do %>
        <%= render partial: 'shared/button_delete', locals: { record: user } %>
      <% end %>
    </td>
  <% end %>
</tr>

app/views/users/_user.html.erb
<%= render partial: 'shared/icon',
    locals: { classes: 'is-small is-left', icon: icon }
%>
<%= user.email %>
<% if current_user.is?(user) %>
  <%= render partial: 'shared/icon',
      locals: { classes: 'is-small is-right', icon: 'user-circle' }
  %>
<% end %>

app/views/users/edit.html.erb
<h1 class="title has-text-centered"><%= t('user.title.profile') %></h1>

<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1 class="title has-text-centered"><%= t('user.title.index') %></h1>

<%= content_tag :div, class: 'tags has-addons' do %>
  <%= render partial: 'shared/button_refresh',
    locals: { classes: 'tag is-primary', reflex: 'click->Application#reload' }
  %>
<% end %>

<table class="table is-fullwidth is-hoverable">
  <thead>
    <tr>
      <th><%= t 'user.email' %></th>
      <th><%= t 'user.group' %></th>
      <th><%= t 'user.role' %></th>
      <th><%= t 'user.enabled' %></th>
      <th><%= t 'user.connections' %></th>
      <% if admin? %>
        <th colspan="1"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <%= render partial: 'row', collection: @users, as: :user %>
  </tbody>
</table>

<hr/>
<%== pagy_bulma_nav(@pagy) %>