config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  devise_for :users, skip: [:passwords] # TODO: :registrations if configured
  root 'sites#home'
  resources :batches, only: %i[index new create destroy] do
    namespace :step do
      %i[preprocesses processes transfers archives].each do |step|
        resources step, only: %i[new create show] do
          post 'cancel'
          post 'reset'
        end
      end
    end
  end
  resources :connections, except: %i[index show]
  get '/connections', to: redirect('/connections/new')
  get '/connections/:id', to: redirect('/connections/%{id}/edit')
  resources :groups, only: %i[index new create edit update destroy]
  get '/groups/:id', to: redirect('/groups/%{id}/edit')
  resources :mappers, only: %i[index]
  get '/mappers/autocomplete', to: 'mappers#autocomplete'
  resources :users, except: %i[create new show] do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
  end
  get '/users/:id', to: redirect('/users/%{id}/edit')
  get '/users/:id/group', to: redirect('/users/%{id}/edit')
  patch '/users/:id/group', to: 'users#update_group', as: 'user_group'

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
end

app/views/shared/_button_create.html.erb
<%= content_tag :span, class: 'tag is-link' do %>
  <%= local_assigns[:text] ? text : t('action.create') %>
<% end %>
<%= link_to path, class: 'create tag' do %>
  <%= fa_icon "plus" %>
<% end %>

app/views/shared/_button_delete.html.erb
<%= content_tag :span, class: 'tag is-danger' do %>
  <%= local_assigns[:text] ? text : t('action.delete') %>
<% end %>
<%= link_to record,
    method: :delete,
    disabled: !manage?(record),
    data: { confirm: t('action.confirm_delete') },
    class: 'destroy tag' do %>
  <%= fa_icon "times" %>
<% end %>

app/views/shared/_button_refresh.html.erb
<%= content_tag :span, class: classes do %>
  <%= t('action.refresh') %>
<% end %>
<%= link_to '#', id: 'refresh', class: 'refresh tag',
    data: { 'reflex': reflex }, onclick: spinner_js do %>
  <%= fa_icon "refresh" %>
<% end %>

app/views/shared/_button_return.html.erb
<%= content_tag :span, class: 'tag is-info' do %>
  <%= local_assigns[:text] ? text : t('navigation.return') %>
<% end %>
<%= link_to path, class: 'return tag' do %>
  <%= fa_icon "undo" %>
<% end %>

app/views/shared/_flash.html.erb
<div class="level has-background-<%= type %>">
  <p class="flash has-text-light ml-3 my-3"><%= message %><span class="delete ml-3"></span></p>
</div>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="content has-text-centered">
    <p><strong>CollectionSpace Batch Import</strong>.</p>
    <p>
      <a href="https://www.collectionspace.org">CollectionSpace</a> is
      an open-source collections management system developed by the community
      and stewarded by <a href="https://www.lyrasis.org">LYRASIS</a>.
    </p>
  </div>
</footer>

app/views/shared/_icon.html.erb
<%= content_tag :span, class: "icon #{classes}" do %>
  <%= fa_icon icon %>
<% end %>

app/views/shared/_navbar.html.erb
<nav id="navbar" class="mb-4" role="navigation" aria-label="main navigation">
  <div class="navbar-menu">
    <div class="navbar-start">
      <%= link_to root_path, class: 'navbar-item' do %>
        <%= fa_icon "home", class: 'mr-2' %>
        <%= t('navigation.home') %>
      <% end %>
      <%= link_to batches_path, class: 'navbar-item' do %>
        <%= fa_icon "cog", class: 'mr-2' %>
        <%= t('navigation.batches') %>
      <% end %>
      <% if admin? %>
        <%= link_to groups_path, class: 'navbar-item' do %>
          <%= fa_icon "user-plus", class: 'mr-2' %>
          <%= t('navigation.groups') %>
        <% end %>
      <% end %>
      <% if admin? %>
        <%= link_to mappers_path, class: 'navbar-item' do %>
          <%= fa_icon "map", class: 'mr-2' %>
          <%= t('navigation.mappers') %>
        <% end %>
      <% end %>
      <%= link_to users_path, class: 'navbar-item' do %>
        <%= fa_icon "users", class: 'mr-2' %>
        <%= t('navigation.users') %>
      <% end %>
    </div>

    <div class="navbar-end">
      <% if impersonating_user? %>
        <%= link_to stop_impersonating_users_path, method: :post, class: 'navbar-item' do %>
          <%= fa_icon "exchange", class: 'mr-2' %>
          <%= true_user.email %>
        <% end %>
      <% end %>
      <%= link_to edit_user_path(current_user), method: :get, class: 'navbar-item' do %>
        <%= fa_icon "user-circle", class: 'mr-2' %>
        <%= current_user.email %>
      <% end %>
      <%= link_to '#', method: :get, class: 'navbar-item' do %>
        <%= fa_icon "inbox", class: 'mr-2' %>
        <%= 0 %>
      <% end %>
      <%= link_to destroy_user_session_path, method: :delete, class: 'navbar-item' do %>
        <%= fa_icon "sign-out", class: 'mr-2' %>
        <%= t('navigation.logout') %>
      <% end %>
    </div>
  </div>
</nav>
<hr/>

app/views/shared/_tabs.html.erb
<ul>
  <% tabs.each do |type, tab| %>
    <li class="<%= tab[:active] ? 'is-active' : '' %>">
      <%= link_to batches_path(tab: type.to_s) do %>
        <span class="icon is-small"><%= fa_icon tab[:icon] %></span>
        <span><%= tab[:title] %></span>
      <% end %>
    </li>
  <% end %>
</ul>